### ISSUE TITLE
wrong url address in the paper

### ISSUE THREAD

**Issue by aakhmetz** [jasonhilton/mortality_bgam#1]
Noticing that in the paper https://doi.org/10.1111/rssc.12299 the reference is "https://github.com/jasonhilton/mortality-bgam", which is a little different (so github does not find it)

**Comment by jasonhilton** [comment]
Thanks so much for spotting this Andrei! I will ask the journal to ammend, and in the meantime I have created a placeholder repo at mortality-bgam to redirect lost travellers here.
